### ISSUE TITLE
How to specify markdownlint flags?

### ISSUE THREAD

**Issue by janosh** [reviewdog/action-markdownlint#11]
Could you provide an example of how the MDL config should be formatted? Like this?

```yml
- name: markdownlint
  uses: reviewdog/action-markdownlint@master
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    reporter: github-pr-review
    markdownlint_flags:
      MD013: false
```

**Comment by skarzi** [comment]
Hi :wave: 

`markdownlint_flags` input is used to define [`markdownlint-cli` CLI flags](https://github.com/igorshubovych/markdownlint-cli#usage) not `markdownlint` configuration
(I know it's quite confusing and we need to think about a better name).
Currently, the only possible way to ignore certain rules is by disabling them in [`markdownlint-cli` configuration file](https://github.com/igorshubovych/markdownlint-cli#configuration), so to solve your problem you need to create such file, e.g.: `.markdownlint.yaml` with the following content:

```yaml
---
MD013: false
```

**Comment by janosh** [comment]
Excellent, that worked. Thank you.

Btw, last I visited this repo, it was called `prologic/action-markdownlint`. Did it become a community effort in the meantime?

**Comment by skarzi** [comment]
To be honest, I don't know, I have started using this action ~1-2 weeks ago. However recently many actions that use `reviewdog` was moved to `reviewdog` organization, so I guess you are right

**Comment by kpocius** [comment]
Sorry for resurrecting and old issue, but I wanted to disable MD013 globally as we use this action in a shared workflow, and spamming all of our repos with `.markdownlint.yaml` files wasn't an option.

Funny enough, all the searches kept leading me back to this issue, so I finally figured it out and here's the answer:
```
- name: markdownlint
  uses: reviewdog/action-markdownlint@master
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    reporter: github-pr-review
    markdownlint_flags: >-
      --disable MD013 -- .
```
You can add more rules as needed.
