### ISSUE TITLE
How to pass multiple parameters to markdownlint-cli?

### ISSUE THREAD

**Issue by Guts** [reviewdog/action-markdownlint#18]
When I write:

```yaml
- name: markdownlint-github-pr-review
  uses: reviewdog/action-markdownlint@v0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    fail_on_error: true
    filter_mode: added
    reporter: github-pr-review
    markdownlint_flags: content/**/*.md
```

But if I do:

```yaml
- name: markdownlint-github-pr-review
  uses: reviewdog/action-markdownlint@v0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    fail_on_error: true
    filter_mode: added
    reporter: github-pr-review
    markdownlint_flags: -i **/template_*.md content/**/*.md
```

it's not working? What am I missing?
